// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3f_s3WJRWUiQcsIb1kMCx63Izz1ZtyWQ',
    appId: '1:677868482625:web:106a40caab0b424372d6c0',
    messagingSenderId: '677868482625',
    projectId: 'fandom-6d48a',
    authDomain: 'fandom-6d48a.firebaseapp.com',
    storageBucket: 'fandom-6d48a.firebasestorage.app',
    measurementId: 'G-3XYSE7CPP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0wkwAEn78AJwsIPMi-rxRLhDOdVWzufE',
    appId: '1:677868482625:android:632bdef403aa5f9172d6c0',
    messagingSenderId: '677868482625',
    projectId: 'fandom-6d48a',
    storageBucket: 'fandom-6d48a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIKMtV3_afNoLPkTHpKj5kLEB_ukLuBSg',
    appId: '1:677868482625:ios:4292fe0c21d0a0f172d6c0',
    messagingSenderId: '677868482625',
    projectId: 'fandom-6d48a',
    storageBucket: 'fandom-6d48a.firebasestorage.app',
    iosClientId: '677868482625-1odfbkahibiuha866dhdqqqamcfrr8j8.apps.googleusercontent.com',
    iosBundleId: 'com.fandomverse.fandomVerse',
  );
}
